name: Capture Screenshot

on:
  schedule:
    - cron: "*/15 * * * *"  # Toutes les 15 minutes
  workflow_dispatch:        # Permet aussi de le lancer manuellement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run screenshot script
        run: node index.js

      - name: Commit screenshot
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/latest.png
          git commit -m "🖼️ Update screenshot [auto]" || echo "No changes"
          git push
